openapi: 3.0.3
info:
  title: "NeoMarket B2C: Корзина + Избранное + Главная"
  version: "0.1"
  description: |
    Проектируется синдикатом Interface.
    Домены: корзина (CRUD), избранное, главная страница (баннеры, подборки).

paths: {}
# Здесь команды Interface описывают свои эндпоинты
